---
version: 2

workflows:
  version: 2
  program-analysis:
    jobs:
      - tcc

jobs:
  tcc:
    working_directory: ~/work
    docker:
      - image: ubuntu:bionic

    steps:
      - run: &apt_install
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive
          apt-get install -y --no-install-recommends
            ca-certificates
            clang
            cmake
            git
            libconfig-dev
            libgtest-dev
            libopus-dev
            libsodium-dev
            libvpx-dev
            llvm-dev
            ninja-build
            pkg-config
            libavutil-dev
            libavcodec-dev
            libavformat-dev
            libavfilter-dev
            libx264-dev
      - checkout
      - name: Build with TCC
        run:
          ./.localrun/run_tcc.sh

