name: github_build

on:
  push:
  pull_request:

jobs:
  linux-asan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get remove g++ && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          clang \
          cmake \
          git \
          libconfig-dev \
          libgtest-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          llvm-dev \
          ninja-build \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavfilter-dev \
          libx264-dev
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-asan

  linux-tsan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get remove g++ && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          clang \
          cmake \
          git \
          libconfig-dev \
          libgtest-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          llvm-dev \
          ninja-build \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavfilter-dev \
          libx264-dev
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-tsan

  linux-alpine-normal:
    runs-on: alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apk update && \
          sudo apk add bash && \
          sudo apk add \
          wget \
          git \
          cmake \
          automake \
          autoconf \
          check \
          libtool \
          rsync \
          nano \
          gcc \
          g++ \
          clang \
          clang-extra-tools \
          clang-analyzer \
          libconfig-dev \
          libsodium-dev \
          opus-dev \
          libvpx-dev \
          x264-dev \
          ffmpeg4-dev \
          ninja \
          pkgconf-dev \
          make \
          yasm \
          file \
          linux-headers \
          binutils \
          gtest-dev \
          llvm-dev
      - run: |
          sudo rm -f /usr/bin/c++;
          sudo rm -f /usr/bin/g++;
          sudo cd /usr/bin/;
          sudo ln -f /usr/bin/clang++ c++;
          sudo ln -f /usr/bin/clang++ g++
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-normal
