name: github_build

on:
  push:
  pull_request:

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  linux-asan:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          clang \
          cmake \
          git \
          libconfig-dev \
          libgtest-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          llvm-dev \
          ninja-build \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavfilter-dev \
          libx264-dev
      - run: git submodule update --init --recursive
      - run: CC=clang .circleci/cmake-asan
