name: ci

on:
  push:
  pull_request:

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  build-nacl:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
