name: custom_tests

on:
  push:
  pull_request:

jobs:
  linux-custom-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get remove g++ && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          clang \
          cmake \
          git \
          libconfig-dev \
          libgtest-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          llvm-dev \
          ninja-build \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavfilter-dev \
          libx264-dev
      - run: git submodule update --init --recursive
      - run: |
          CC=clang cmake -B_build -H. -GNinja \
          -DCMAKE_INSTALL_PREFIX:PATH="$PWD/_install" \
          -DCMAKE_C_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
          -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
          -DCMAKE_EXE_LINKER_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
          -DCMAKE_SHARED_LINKER_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
          -DMIN_LOGGER_LEVEL=DEBUG \
          -DMUST_BUILD_TOXAV=ON \
          -DNON_HERMETIC_TESTS=OFF \
          -DSTRICT_ABI=OFF \
          -DUSE_IPV6=OFF \
          -DAUTOTEST=OFF \
          -DBUILD_MISC_TESTS=OFF \
          -DBUILD_FUN_UTILS=OFF
          cd _build
          ninja install -j"$(nproc)"

      - run: |
          pwd
          ls -al
          export PKG_CONFIG_PATH="$PWD"/_install/lib/pkgconfig
          export LD_LIBRARY_PATH="$PWD"/_install/lib
          ls -al "$PKG_CONFIG_PATH"
          clang -g -O1 -fno-omit-frame-pointer -fsanitize=address \
          $(pkg-config --cflags toxcore libavcodec libavutil x264 opus vpx libsodium) \
          $(pkg-config --libs toxcore libavcodec libavutil x264 opus vpx libsodium) \
          ./custom_tests/toxav_msi_stress_test_01.c \
          -o toxav_msi_stress_test_01
          ldd toxav_msi_stress_test_01
          ./toxav_msi_stress_test_01


